version: '3.8'

services:
  kanidm:
    image: kanidm/server:1.2.2
    container_name: kanidm
    ports:
      - "8443:8443"
      - "3636:3636"
    volumes:
      - kanidmd:/data

volumes:
  kanidmd:
    external: true
    name: kanidmd
    # contains tls certs and server.toml
